# Generated by Django 4.0.1 on 2022-03-17 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depart',
            new_name='Department',
        ),
    ]
