# Generated by Django 4.0.1 on 2022-03-17 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_rename_depart_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='title',
            new_name='name',
        ),
    ]
