# Generated by Django 4.0.1 on 2022-03-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_rename_title_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='img',
            field=models.FileField(default='admin/管理员头像.svg', max_length=128, upload_to='admin/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='department',
            name='img',
            field=models.FileField(max_length=128, upload_to='depart/', verbose_name='科室图片'),
        ),
    ]
