# Generated by Django 4.0.1 on 2022-04-04 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_admin_img_alter_department_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='img',
        ),
    ]
