# Generated by Django 4.0.1 on 2022-04-08 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_admin_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('level', models.SmallIntegerField(choices=[(1, '医师'), (2, '主治医师'), (3, '副主任医师'), (4, '主任医师')], verbose_name='等级')),
                ('salary', models.IntegerField(verbose_name='工资')),
                ('day', models.CharField(max_length=32, verbose_name='工作时间')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='所属部门')),
            ],
        ),
    ]
